### PR TITLE
Remove hardcoded `XDG_DATA_DIR`s

### LINKED ISSUE #2: Hardcoded paths in `default_paths` ignore local setup
The `default_paths` function currently returns a list of hardcoded paths: https://github.com/pop-os/freedesktop-desktop-entry/blob/ccb4e86e801f603041d8cae5205138f9ea2a26f8/src/lib.rs#L287-L318

This has two problems:
- It ignores user-configured paths.
- It includes paths that the user has not configured.

Both problems can results in unexpected behaviour inconsistent with system setup. The correct approach is to use `XDG_DATA_DIRS`, which will include the paths in the above linked function (if appropriate), but many include additional paths configured in the local system. For example, in my current setup it's:

    /home/hugo/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share/:/usr/share/

Note that `/usr/local/share/` is currently ignored by `default_paths()`.

### PR DESCRIPTION
**Pull request by WhyNotHugo**
Remove hardcoded directory paths, and use the read the applicable
environment variables. This avoids ignoring locally configured paths,
and also avoid picking up paths explicitly removed by the user.

The `PathSource` value is now a best-effort guess, since it's possible
that paths don't match any expected values (e.g.: users can add anything
like `/opt/my-toolkit/`.

Note that, while `xdg` is a new direct dependency, it was already a
transitive dependency, so there's no no dependencies here.

The potential panic (due to `unwrap()`) can happen under the exact same
scenario: when failing to determine the home path. This should ideally
be fixed, but is slightly out of scope.

I have to point out that I'm not convinced that `PathSource` is a great
idea; especially since we're mostly trying to guess them. Probably
inspecting the desktop entry files would be a better idea. Flatpak
applications in particular, include a `X-Flatpak` key to recognise them.
I'm unusure about nix entries. However, removing `PathSource` would be a
larger breaking change, so I'd rather discuss that separately.

Fixes #2

### CODE REVIEW

File: src/lib.rs [hunk 1]
```diff
@@ -279,42 +281,45 @@ pub enum PathSource {
...
+                PathSource::SystemFlatpak
+            } else if dir.starts_with("/var/lib/snapd") {
+                PathSource::SystemSnap
+            } else if dir.starts_with("/nix") {
+                PathSource::Nix
+            } else if dir.to_string_lossy().contains("/flatpak/") {
+                PathSource::LocalFlatpak
+            } else if dir.starts_with(&data_home.as_path()) {
+                PathSource::Local
+            } else if dir.to_string_lossy().contains(".nix") {
```
Comment (mmstick) [inline src/lib.rs:314]: This should also check if the directory is in `/nix/var/nix/profiles/per-user/`

**Comment by mmstick** [comment]
> However, removing PathSource would be a
larger breaking change, so I'd rather discuss that separately.

I'd be okay with separating that functionality into a `PathSource::guess_from(Path)` implementation.

**Comment by WhyNotHugo** [comment]
> I'd be okay with separating that functionality into a PathSource::guess_from(Path) implementation.

Yeah, that sounds a lot more sensible. I'll update the PR to do that.
